### ISSUE TITLE
Operation Doubtfire extension: replace old functions

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#106]
Looks like some functions contain some of the older functions as well.  I can update FuncLib as well.

VKC update 05/10/2016: here are the functions to be searched for and replaced:
- [x] ERRR_screen_check
- [x] maxis_check_function
- [x] navigate_to_screen
- [x] write_editbox_in_case_note
- [x] write_new_line_in_case_note
- [x] write_new_line_in_SPEC_MEMO
- [x] worker_county_code_determination
- [x] write_TIKL_function

**Comment by theVKC** [comment]
Thanks @IlseFerris!

**Comment by theVKC** [comment]
@IlseFerris, can I bump this? If you won't have time, I will mark it as help wanted or try and knock it out myself.

**Comment by IlseFerris** [comment]
We take these couple of issue on together, eh?

**Comment by theVKC** [comment]
Let's do it.

**Comment by theVKC** [comment]
Can I bump this @IlseFerris? I want to get rid of the depreciated functions before the end of the year, ideally this month.

**Comment by theVKC** [comment]
Next week?

**Comment by IlseFerris** [comment]
Sounds good to me, let's get something on the books

**Comment by theVKC** [comment]
@IlseFerris, we need to actually get this done for real.
