### ISSUE TITLE
call autofill_editbox_from_MAXIS(HH_member_array, "SWKR", SWKR) does not exist. 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#117]
call autofill_editbox_from_MAXIS(HH_member_array, "SWKR", SWKR) does not exist. Would be nice if it did.

**Comment by theVKC** [comment]
Want this @IlseFerris? If not, I think I need to close it due to lack of interest.

**Comment by IlseFerris** [comment]
Yes I'll take this

**Comment by theVKC** [comment]
Any update @IlseFerris? I can take it if you'd like.

**Comment by IlseFerris** [comment]
I made a commit directly into the file a few days ago. I wasn't 100% on how to test this though.

**Comment by theVKC** [comment]
Set to Run Locally and test it?
