### ISSUE TITLE
MAXIS footer finder function issue

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#125]
The find_variable if returning a string which when compared using isnumeric is giving a false triggering the function to default to current month.

**Comment by CDPotter** [comment]
I'm also concerned that the output is getting used incorrectly, I've notices scripts using MAXIS_footer_month after this function why does it assign value to footer_month and footer_year in the first IF but not the 2nd?

**Comment by theVKC** [comment]
@IlseFerris, have you had a chance to look at this issue at all? I know that you did some work here at one point. I'm curious to know your thoughts on the subject.

**Comment by IlseFerris** [comment]
I haven't yet, and I won't have time to dive in this week.  SNAP stuff has taken over my life.

**Comment by CDPotter** [comment]
@RobertFewins-Kalb and I also noticed that the exiting variables in the function were MAXIS_footer_month and MAXIS_footer_year, however in the first IF statement footer_month and footer_year were being defined. We are worried that there might be some confusion between which variables to use and pull through and some scripts having mixtures of footer_month and MAXIS_footer_month.

**Comment by theVKC** [comment]
I think we should move towards `MAXIS_footer_month` as part of the whole "No Mainframe Left Behind" approach, but I'm open to suggestions.

**Comment by RobertFewins-Kalb** [comment]
But footer month is only relevant in maxis.

**Comment by theVKC** [comment]
Hmmmm... well, if you want to change it, be my guest.

**Comment by CDPotter** [comment]
I don't know if we need to change everything back but I guess we just need to be more vigilant when revising scripts. It seems like the change wasn't completely thorough as there are still instances of footer_month being used in the same scripts as MAXIS_footer_month (like this function currently does.)

**Comment by theVKC** [comment]
Resolved with #126.
