### ISSUE TITLE
write_panel_to_MAXIS_SHEL now misoriented

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#135]
It looks like we are now off by 4 columns...how long has "Subsidized (Y/N)" been "HUD Subsidized (Y/N)" ?!?

**Comment by theVKC** [comment]
@RobertFewins-Kalb, did we fix this ever?

**Comment by RobertFewins-Kalb** [comment]
I have a fix waiting. I didn't want to overload the number of FuncLib pull requests b/c merge conflicts. I will submit a pull request with all the updates we have made for Krabappel.

**Comment by theVKC** [comment]
FuncLib is all cleaned up pull-request wise. Go nuts!

**Comment by theVKC** [comment]
@RobertFewins-Kalb any update?

**Comment by RobertFewins-Kalb** [comment]
Fixed

**Comment by theVKC** [comment]
When? Any idea what pull request it was? (This is why we need to tag issues in pull requests.)

**Comment by RobertFewins-Kalb** [comment]
15 days ago

**Comment by theVKC** [comment]
Thanks for linking back to it!
