### ISSUE TITLE
Bug on navigate_to_MAXIS_screen when in Program History

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/BZS-FuncLib#136]
If this function is run from program history and it is trying to go to something else in the 'CASE' function - such as CASE/NOTE - The Command line is not editable and the script thinks the worker is in Inquiry. 
Looks like CASE/MNCV has the same issue (but I didn't even know that area existed so not sure how much that matters).

We could write something to check for 'Program History' and PF3 before attempting to update the Command line with the new screen. Maybe it needs something a little bit more generic incase there are other Function/Command combinations that have this issue.

**Comment by theVKC** [comment]
@C-Love has this, but as she hasn't contributed to FuncLib yet, I can't assign it to her directly.
