### ISSUE TITLE
VBscript cannot really sort numeric arrays...

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#153]
Hows about a custom function to do that?

**Comment by theVKC** [comment]
Yes + yes + (1000 * yes)

**Comment by RobertFewins-Kalb** [comment]
resolved by #154

**Comment by theVKC** [comment]
@RobertFewins-Kalb: please don't close issues if there's a pending pull request out there. I use that for tracking for release notes. :)
