### ISSUE TITLE
Create function to display MAIN MENU dialog from a simple list

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#163]
Scriptwriters are struggling with maintaining the existing dialog. My solution:
1. Create an array of all the different NOTES scripts (multidimensional, with 0 being the name, 1 being the description, 2 being the URL).
2. A function can take that array and through magic or sorcery turn it into a dialog.

If anyone feels up to an engineering challenge, I'll mark this as help wanted. But I'm hoping to have it wrapped up this release or next.

**Comment by C-Love** [comment]
I am thinking the sorcery would include additional dimensions to the array that inform the sizes of the dialog. This seems like it would solve some of our dimming issues. 

I have not done much with building functions but I would like a shot at this.

**Comment by theVKC** [comment]
It's yours!

I think we can dynamically determine the appropriate size of the dialog using math. Something like `dialog_size = x * 15` where `x` is the ubound of the array?

**Comment by theVKC** [comment]
Per @C-Love: I'm taking this one for her.

**Comment by theVKC** [comment]
This is still being tested in the main repo. So, I'm going to move it to April.

**Comment by theVKC** [comment]
OK folks, realistically I don't think I can get this done this month or next. @MN-Script-Team/functions-library-contributors: it shouldn't be too difficult to add an extra class for creating buttons (which behave like tabs) to specialize certain scripts. I just don't know when I'll have time. It needs to happen though, the standardization from that will greatly help in our workflow projects, and I'm guessing Child Support will want this too.

**Comment by theVKC** [comment]
I'm intrigued by @RobertFewins-Kalb's work here: https://github.com/MN-CS-Script-Team/PRISM-Scripts/blob/master/Script%20Files/NOTES/NOTES%20-%20MAIN%20MENU.vbs

I think I'm going to take it and use it here. I have a theory and it involves https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/2159.

**Comment by theVKC** [comment]
Obsoleted by the Win10 craziness.
