### ISSUE TITLE
HC income estimator only being read in CM+1

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#172]
We have heard some suggestions to change the function so that the scripts don't grab out of date HC income estimator amounts. For example:

You get a late HC renewal, you're processing it and cannot update the income estimate in any other month than CM+1 as such when the script is run for 01/16 it grabs the old HC income estimator. 

Thoughts?

**Comment by IlseFerris** [comment]
Makes sense to me.

**Comment by theVKC** [comment]
Hmmm. Thought it already did this. Maybe I imagined that.

Should it _always_ go into CM+1, or only read the HC amount if you're already in CM+1 (I lean toward the latter but am open to suggestions)

**Comment by CDPotter** [comment]
I'd say the later, you can only really trust the info from CM+1 in there.

**Comment by theVKC** [comment]
@CDPotter: did you want this?

**Comment by theVKC** [comment]
Marked this for the next release, I'd like it done (or removed) by the 16th. :)

**Comment by CDPotter** [comment]
I can take it

**Comment by theVKC** [comment]
Thank you @CDPotter!

**Comment by CDPotter** [comment]
Welp I look like a dummy... Same case with the JOBS panel. I've emailed the group that suggested the issue to let them know it isn't an issue. This can be closed. 
![2016-02-04 10_29_49-mozilla firefox](https://cloud.githubusercontent.com/assets/7841989/12821751/5aa0f730-cb2a-11e5-83a0-463a2737d06f.png)

**Comment by theVKC** [comment]
Thanks for catching that!
