### ISSUE TITLE
check_for_MMIS function needs to be added to FuncLib

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#182]
It just lives in the MHC enrollment script stored locally. This could be useful as more MMIS scripts could be on the horizon.

**Comment by theVKC** [comment]
Is this coming shortly? Also, do any other MAXIS scripts use check_for_MMIS? Thinking we should do a Ctrl-F check on all scripts just to be safe. Seems other scripts might use local functions which could conflict with this one...

**Comment by IlseFerris** [comment]
I just checked all the state supported scripts that are in master, and none of the scripts use this function.

**Comment by theVKC** [comment]
Fantastic. Thank you!!!!!

**Comment by IlseFerris** [comment]
You're welcome :)
