### ISSUE TITLE
New standard for case_number/footer_month etc

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#184]
We should take time to discuss a new standard for case_number in the form of MAXIS_case_number. We need to evaluate feasibility of this. (tabled for 2/22/16 hackathon)

VKC update 05/10/2016:

The following are the things I'll be updating ASAP:

- [x] `case_number` => `MAXIS_case_number`
- [x] `footer_year` => `MAXIS_footer_year`
- [x] `footer_month` => `MAXIS_footer_month`
- [x] `PMI` => `MAXIS_PMI`

**Comment by theVKC** [comment]
Also replacing instances of `footer_month` and `footer_year` with `MAXIS_footer_month` and `MAXIS_footer_year`. I'd be interested to hear from PRISM scriptwriters on this too. Aligning things seems logical.

**Comment by RobertFewins-Kalb** [comment]
PRISM_footer_month does not exist. 

Going with MAXIS_case_number and PRISM_case_number makes sense, but other than that, I'm not seeing any overlap that would justify going through and redefining MAXIS_ and PRISM_

**Comment by theVKC** [comment]
Oooh! I have one! In many internal data points, we refer to it as "MAXIS footer month". I've also heard quite a few counties do that. 

I also believe Data Warehouse alternates between using "MAXIS footer month" and "Benefit Period" depending on the model or the definition. I see merit in differentiating between something MAXIS-specific as well if we are looking both at system modernization and MMIS scripting on the horizon (MMIS appears to use "benefit period" or "elig begin month").

**Comment by IlseFerris** [comment]
Geek points issued to @theVKC for the use of data points...LOL!

**Comment by theVKC** [comment]
This needs to happen, but I want it to go out Monday after hackathon (and before training).

**Comment by theVKC** [comment]
`PMI` does not exist in FuncLib. That means with #224, this issue is closed!

**Comment by IlseFerris** [comment]
Nice work and thank you!
