### ISSUE TITLE
Move create_dynamic_calendar_dialog from REVS scrubber over to FuncLib, add parameters

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#185]
Here are the extra parameters I picture:

* No-go date range (an array I'd think)
* Disable weekends
* Custom text on dialog

Anything else?

**Comment by theVKC** [comment]
I won't have time to do this in the next month or so. :(

**Comment by IlseFerris** [comment]
This might not be ready by Friday. Can we change the release to June?

**Comment by theVKC** [comment]
I keep running into problems finding time for this. Perhaps @CDPotter or @RobertFewins-Kalb would be interested?

If nobody is interested by next hackathon, I'm closing the issue. :(

**Comment by CDPotter** [comment]
I could give it a shot.

**Comment by theVKC** [comment]
Thank you @CDPotter!
