### ISSUE TITLE
BUG: Autofill editbox from maxis. ACCT section doesn't account for 10+ accounts

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#189]
One worker has exactly 10 active bank accounts for a client. The script only reads the 1 digit so it's reading "1" and thinking it's done. Just need to change it to read 2 digits. There may be other asset panels that need this fix. 

I tested on a fake case and was able to make at least 21 acct panels before I gave up trying to find a limit.

**Comment by CDPotter** [comment]
Strangely enough the limit is 96 asset panels.

**Comment by theVKC** [comment]
@CDPotter: was this successfully added? I.e. did you pull request?

**Comment by CDPotter** [comment]
Only ACCT panel was still reading 1, the other asset panels were fine. (CARS, REST, SECU, OTHER)
