### ISSUE TITLE
Call autofill from MAXIS for WREG isn't pulling counted months into scripts

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#196]
I've got this.

**Comment by theVKC** [comment]
@IlseFerris: are you sure you want it to do this for all cases?

**Comment by IlseFerris** [comment]
I am also adding functionality to pull ABAWD counted months and 'Second set' of counted ABAWD months information to the autofill function, as well as the dates of the counted months.
