### ISSUE TITLE
Small bug in the new INSA autofill

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#20]
It's really not a super big deal, and it's actually a pretty easy fix, so I might take it tonight.

It is doing a peculiar thing with the household member numbers:

![2015-02-06 18_23_34-hcapp dialog part 2](https://cloud.githubusercontent.com/assets/5701751/6089744/761023a8-ae2d-11e4-9ad4-26c7823735d4.png)

It's also adding the name of the first INSA in to the second record. This is an easy fix (set variable to = "" somewhere in the beginning of the loop). I'll end up getting to it this weekend if @lpshanley doesn't. And that's OK, because his help on this was HUGE!

**Comment by lpshanley** [comment]
Let me know if you didn’t have a chance to get to this. I was working on my bathroom all weekend alongside it being my fiancés birthday and our anniversary lol. If you didn’t have a chance to look at it let me know and I’ll check it out over lunch.

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
I didn't get a chance. Enjoy!


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment]
Is there a small description of the issue on git?

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
Just in this chain. I don't know exactly where the issue lies yet. If you don't have time today I'll take care of it this afternoon for sure. :)

**Comment by lpshanley** [comment]
All done and committed. :)

**Comment by lpshanley** [comment]
Problem solved Crisis averted. ☺

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
Hey @lpshanley, did we ever get this pushed? Can anyone out there check on this to see if it's working? @RobertFewins-Kalb? @CDPotter? @IlseFerris?

**Comment by RobertFewins-Kalb** [comment]
I will add it to my Pressley scenario. I've been working the bugs out of each panel. I can add an INSA panel to the scenario.

**Comment by RobertFewins-Kalb** [comment]
Sidebar: This got me looking at Krabappel. INSA needs work.

**Comment by lpshanley** [comment]
Hmmm... I’m not sure. I know that I made the fix for it pushed it because you had tested it and sent me screen shots! Im not sure if this got merged forward to any of the released however.

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
Any chance you can peruse the code and tell me if you think we took it?

**Comment by lpshanley** [comment]
Yea on my break at 10 I’ll have a look-see ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P
