### ISSUE TITLE
JOBS panel is a' changin'

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#227]
HC income estimator will be at 19, 48
GRH income estimator (new) will be at 19, 71
SNAP income estimator is in the same spot.

Functions affected: 
add_JOBS_to_variable(variable_name_for_JOBS)
write_panel_to_MAXIS_JOBS

**Comment by theVKC** [comment]
Thanks @CDPotter!

**Comment by theVKC** [comment]
This is pretty critical, so we're delaying release to get it built and tested.
