### ISSUE TITLE
Convert_date_to_MAXIS_Footer_Month is creating 1 digit Month

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/BZS-FuncLib#232]
This function is creating the footer month to be only 1 number long for Jan - Sept. Looks like the length logic is after the pulling of the month portion of the date. 

I have the fix.

This is what is breaking Application Received for cases that have not yet been pended.

**Comment by theVKC** [comment]
@C-Love, was there a regular scripts issue which is solved by this?

**Comment by C-Love** [comment]
Approved Programs was affected but I could not find an issue for it. I think maybe we just talked about it last week but never created an Issue.

**Comment by theVKC** [comment]
Sounds good. I'll make sure that's in the release notes.

**Comment by theVKC** [comment]
This is causing Approved Programs to have an impassable in agencies where the user entering the note and APPLing doesn't have STAT access. As such, I'm upgrading this to critical.
