### ISSUE TITLE
Reading ABAWD Status

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#24]
A bug was reported by a worker in Anoka County. The variable "read_abawd_status" is making the following determination...
IF read_abawd_status = 10 OR read_abawd_status = 11 OR read_abawd_status = 13...

It is causing an error when the script encounters an ABAWD status = "__"

Do we want to turn those values for comparison into strings or demand that workers be updating ABAWD statuses?

**Comment by RobertFewins-Kalb** [comment]
My vote is to demand that workers be updating ABAWD statuses and not leaving that value blank.

**Comment by theVKC** [comment]
I get that, but I vote for converting it to a string. Once the CAF script starts yelling at you about stuff you didn’t do in MAXIS, it becomes an ACTIONS script more than a case note. Plus, I’m betting there’s some legitimate reasons why it wouldn’t necessarily be updated right away. Putting a “member 01 has no ABAWD status coded” string in should be enough for our users. I do think an ACTIONS script for “check _____ status”, which would give a pop-up of issues like this (as well as PIC not being updated, question marks without expedited, etc) would be helpful.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by theVKC** [comment]
Where did we land on this? Can I close this issue @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
Let's leave it open. I'd like to have @mldietz work on it as part of the upgrade where ABAWD and FSET codes are being read.

**Comment by mldietz** [comment]
Sounds good to me

**Comment by theVKC** [comment]
Woohoo! @mldietz, I'l add you to the FuncLib contributor group, and assign the task to you. Good luck, and let us know if you need anything!

**Comment by theVKC** [comment]
@mldietz pushed this with #61.
