### ISSUE TITLE
Add verbiage to start_a_blank_CASE_NOTE

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/BZS-FuncLib#240]
Function start_a_blank_CASE_NOTE has a case note check that alerts the worker they might be in inquiry. Should add a note that the worker may not have proper authorization to create a case note as a troubleshooting option.

**Comment by theVKC** [comment]
Can we add OK-cancel functionality to this @MelissaFox-Stearns?

**Comment by theVKC** [comment]
Any update on this one, @MelissaFox-Stearns? I know things have been tight at Stearns right now. If you haven't gotten around to it, perhaps someone else may take this on?

**Comment by theVKC** [comment]
marking this as help-wanted. Anyone want to hit this one real quick? @IlseFerris? @C-Love? @courtrightd? @RobertFewins-Kalb? @CDPotter?

**Comment by IlseFerris** [comment]
I can knock this out
