### ISSUE TITLE
Idea: script blacklist

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#241]
I want to create an option (thanks to #163) which allows an agency to blacklist certain scripts with an update to Global Variables. I will crosslist this in the MAXIS list. I could see something like that being helpful for PRISM as well (I've briefly discussed this with the PRISM scriptwriters here).

This should be added to the function from #163, which is due to be pulled shortly.

**Comment by RobertFewins-Kalb** [comment]
PRISM scripts already has a way for agencies to blacklist scripts.

**Comment by theVKC** [comment]
From what I can see, PRISM's process is whitelisting and not blacklisting. It appears to involve a GitHub list (maintained by GitHub admins) which agencies _opt in_ to. The new MAXIS method would be an _opt out_ process that's managed within-the-agency without involving a pull request (which requires an admin to accept). I'm also working in "forced overrides" which prevent a user from blacklisting certain scripts like CAF or Paystubs Received. 

The users here told me that this concept may be an improvement (or at least a nice feature). In any case, this will be included in MAXIS. PRISM is free to deploy it if they want.

**Comment by RobertFewins-Kalb** [comment]
OK, I have been poking around with the script below, and I like you version. That is slick.

![image](https://cloud.githubusercontent.com/assets/7842016/16210698/0b3e2a7e-3703-11e6-87b0-e6ffcedeacc4.png)

**Comment by theVKC** [comment]
Thank you!?

Not entirely certain how your screenshot discusses the issue. Perhaps a bit of explanation would help me make sense of it?

**Comment by theVKC** [comment]
Totally backburnered. If anyone wants to be the hero, I'm open to that. @RobertFewins-Kalb maybe?

**Comment by theVKC** [comment]
Closing due to lack of interest.
