### ISSUE TITLE
New function >> gather stats by supervisor

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#243]
Similar to `create_array_of_all_active_x_numbers_in_county(array_name, county_code)` hows about a custom function that navigates to REPT/USER to pull all X1 numbers under to that supervisor. Would be nice for supervisors to check caseload stats for their staff.

**Comment by theVKC** [comment]
I like it. Shall I assume you want this one?

**Comment by RobertFewins-Kalb** [comment]
yes please. I will submit a pull request today
