### ISSUE TITLE
Bug -- write_panel_to_MAXIS_ACCT needs updating

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#245]
STAT/ACCT has been updated. Verif code field has moved from 10, 63 all the way to 10, 64.

**Comment by RobertFewins-Kalb** [comment]
looks like it's also dependent on the month

**Comment by theVKC** [comment]
Want it? We should be able to get it fixed before Monday's release, right? I can't imagine it's that hard.

**Comment by RobertFewins-Kalb** [comment]
Yes please. I can run a scenario with a bunch of panels to find any other bugs and submit fixes this week.

**Comment by theVKC** [comment]
Thanks for doing it! :)

**Comment by RobertFewins-Kalb** [comment]
Master and Release or just Master?

**Comment by theVKC** [comment]
Just master. Release is on Monday and I'm betting we can wait that long.
