### ISSUE TITLE
Remove functions specific to NOTES - BURIAL ASSETS

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#247]
These 3 functions are specific to NOTES - BURIAL ASSETS, and should be moved back to the script itself, and removed from FuncLib. Functions are:
* new_BS_BSI_heading
* new_CAI_heading
* new_service_heading

@CDPotter is wiling to take this for the July release since he is working on enhancements for the NOTES - BURIAL ASSETS script.

**Comment by CDPotter** [comment]
Once we get the pull below, pulled I can remove these functions. 

https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/pull/2378
