### ISSUE TITLE
Call for input: removal of sort_numberic_array.... functions from FuncLib

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#248]
sort_numeric_array_ascending(values_array, separate_character, output_array) 
AND
sort_numeric_array_descending(values_array, separate_character, output_array)

Both these functions do not exist in any current MAXIS scripts. I propose that we remove these functions from the FuncLib as to clean up the FuncLib. @RobertFewins-Kalb, do you have anything local or in PRISM scripts that use these functions?

**Comment by RobertFewins-Kalb** [comment]
Why remove them? vbscript has no way of sorting a numeric array. Those functions give script writers the ability to sort numeric arrays.

**Comment by IlseFerris** [comment]
Why keep them? True, vbscript doesn't have a functions that have this ability, but if MAXIS scripts aren't using the function then why keep it in the FuncLib?

**Comment by theVKC** [comment]
@RobertFewins-Kalb: I believe we ran into problems when implementing it. Perhaps a brief set of instructions on how to properly use the function would help the impasse.

**Comment by RobertFewins-Kalb** [comment]
I could go either way if it's not working.

**Comment by theVKC** [comment]
We can always go back through the GitHub history to retrieve it.

@IlseFerris, can you depreciate this along with #252? I'm closing this issue.

**Comment by IlseFerris** [comment]
Will do. 
Also adding script_end_procedure_wsh to the list.
