### ISSUE TITLE
Add date_array_generator to FuncLib

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#249]
@theVKC created this function for the ABAWD banked months fiater. It needs to be added to the FuncLib. Fact.

**Comment by IlseFerris** [comment]
This one's in ACTIONS - ABAWD banked months fiater. Just so you know where to find it.

**Comment by theVKC** [comment]
@IlseFerris: any chance you can take this one for me? I'm swamped over here. I know it's been created and all... #ugh

**Comment by IlseFerris** [comment]
Sure thing, I'll have it done by the end of the week.

**Comment by theVKC** [comment]
Thank you! :sheep:
