### ISSUE TITLE
simplify navigation functions

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#25]
Rather than have an EMWriteScreen "X", row, col and a transmit, how's about a custom function like this...

FUNCTION go_to(input_value, row, col)
     EMWriteScreen input_value, row, col
     transmit
END FUNCTION

**Comment by theVKC** [comment]
I like the idea, but not calling it “go_to”. Any other ideas?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
enter_value_and_transmit

**Comment by theVKC** [comment]
How about this: “enter_subscreen(x, y)”, and it always does the “x” and transmits?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
If we make it not “X” then it can be implemented in PRISM

**Comment by theVKC** [comment]
That’s true… very true…


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, do you want this one?

**Comment by theVKC** [comment]
@RobertFewins-Kalb, bumping again. Did you not add something to PRISM for this that would work?

**Comment by RobertFewins-Kalb** [comment]
Yes! The function "write_value_and_transmit(variable, row, column)" EMWrites a value at the inputted coordinates and transmits. I can submit a new function to the FuncLib...
Sorry...I've been trying to get to my github homework done.
