### ISSUE TITLE
Retire depreciated functions 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#252]
There are 7 functions that still appear the FuncLib that have been removed from MAXIS scripts AND from FuncLib functions from the Operation Doubtfire project. These functions include:
memb_navigation_next
memb_navigation_prev
navigation_buttons
panel_navigation_next
panel_navigaton_prev
stat_navigation
step_through_handling 

I have reconfirmed that these functions are not in any scripts. I propose that we add a message box warning users of these functions that they will need to be updated for the July release, then remove them from the FuncLib entirely for the August or September release. 

Go ahead, and assign to me for the July release.

**Comment by theVKC** [comment]
Thank you!

**Comment by theVKC** [comment]
Can we also add `script_end_procedure_wsh` to this list? Please and thank you!
