### ISSUE TITLE
Issue with worker_county_code_determination: showing state folks if you're a state person

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#256]
Ruth is having a problem getting the PND2 script working for her since a recent update. We'd been making changes to PND2 and these functions but it doesn't seem to have resolved this issue. I'm on this for July.

**Comment by theVKC** [comment]
@CDPotter, you might want to take a look at this one. I had been working on it for Ruth but didn't have time to complete it. I'm going to remove myself from this issue, I think you should take it and coordinate a fix with Ruth.

**Comment by CDPotter** [comment]
Looks like the bulk pnd2 script uses the wrong variable, two_digit_county_code vs the complete worker_county_code(which is what the output of get_county_code) I'm gonna close this open new issue and fix.
