### ISSUE TITLE
script_end_procedure: allow "pass through" error message which prevents MsgBox

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#257]
For example, let's say you want the stats database to register that the user pressed cancel. WIth this update I want to do, if the first parameter is "~PT: user selected cancel", the database will show "user selected cancel" and the user won't have to get a MsgBox with that info. This allows scripts to pass error reporting without needing to provide an annoying pop-up.

On it for CSES scrubber.

**Comment by theVKC** [comment]
Note: OK, I can see we already have `CANCEL BUTTON SELECTED`, but that only affects cancel buttons. I want to use this pass through for other things, like error tracking. Basically, I want to pass the database information without the worker having to push a button. That's fair, right?

**Comment by IlseFerris** [comment]
Sounds like the only way to go for our users, woot woot!
