### ISSUE TITLE
add_JOBS_to_variable needs to be  updated to read GRH PIC

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#272]
This function reads the HC estimator and the SNAP PIC. Since there is a GRH PIC now, we'll need it to read that one too.

**Comment by theVKC** [comment]
Do you want it, @IlseFerris?

**Comment by IlseFerris** [comment]
Oh sure ;)

**Comment by theVKC** [comment]
Think you can get it done today? It is the last day before the freeze.

**Comment by IlseFerris** [comment]
I'm sure as heck going to try!
