### ISSUE TITLE
Rewrite CAAD noting functions to use EMWriteScreen

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#277]
Right now, they use EMSendKey. Very slow. We fixed this in MAXIS.

This was originally in PRISM-Scripts as https://github.com/MN-CS-Script-Team/PRISM-Scripts/issues/349. Closing there because this is opened.

**Comment by theVKC** [comment]
Per https://github.com/MN-Script-Team/DHS-PRISM-Scripts/issues/560, this function appears to be causing issues. So, I'm prioritizing a fix and marking this now as a bug.

**Comment by levesswe** [comment]
Any update on this?  Users are still having issues with note scripts malfunctioning and I think this update would help.

**Comment by theVKC** [comment]
We switched the process to be a new function called "write_variable" which encompasses all of the other functions. Unfortunately, recent events have sidelined much of the FuncLib work. Trying to wrap up some non-script-related things and then deep diving. I'm also working on getting the scripts favorites buttons alive and well.

**Comment by levesswe** [comment]
OK, thanks!

**Comment by theVKC** [comment]
It's official: #310 should resolve this. Closing.
