### ISSUE TITLE
Create update_scripts function for checking for script/Power Pad updates and applying them

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#279]
I believe this should be created as a function so that both PRISM and MAXIS scripts can utilize it.

This allows https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/2101 to become a simple redirect to this function.

Parameters:
- [ ] Check if you have read/write access to Global Variables
- [ ] If you have read/write, show a dialog with all of the Global Variables settings
- [ ] Based on user selection, update Global Variables file
- [ ] Encourage user to test scripts
- [ ] Allow users to add new variables (variable name) and the default value(s) for that variable.
- [ ] Grabs newest Power Pad if a new one is available (use last_updated_date for that)
- [ ] Grabs new redirect files if new ones are available (use last_updated_date for that)

On it for September release.

**Comment by theVKC** [comment]
@CDPotter, this mirrors your work on MAXIS, no? Creating a function that does the above would resolve both MAXIS and PRISM issues.

**Comment by theVKC** [comment]
@CDPotter, I presume this may not be ready by Friday, right? That's fine by me, I am comfortable kicking this one down a bit.

**Comment by CDPotter** [comment]
Correct, I haven't had a chance to do the power pad function and the rest is currently not very dynamic.

**Comment by theVKC** [comment]
Good deal. No worries, at least from my end, this is less important than other things.

**Comment by CDPotter** [comment]
Finally getting a chance to look at this again. Do we really want people using the script to add variables to their globvar file? Seems a bit error prone to me. We'd also have to account for comments on that variable and then making the dialog reflect that newly added variable.

**Comment by theVKC** [comment]
Yes, I think we should. Essentially, it can load a GlobVar file, read it to a dialog, provide comments as text under each selection, then create a brand new GlobVar file which overwrites the previous. Essentially, ensuring our GlobVar and counties have the latest-and-greatest.

**Comment by CDPotter** [comment]
I get that but in order to use the script correctly you'll have to have some understanding of variables and defining them. You'd have to write the name of the new variable (correctly); use a dropdown or something for the =, >, etc; write the correct value; and write a comment.

At that point wouldn't it just make sense to edit the file by hand? I figured this was more-so a tool for non-writer users to be able to edit their global variable values more easily.

**Comment by theVKC** [comment]
It is, but I don't follow you on the "too complex" side of things. They wouldn't directly be adding variables, the script would simply ask them for whatever's relevant, based on whatever variable's we've added.

**Comment by CDPotter** [comment]
I was talking about checkbox number 4 above: Allow users to add new variables (variable name) and the default value(s) for that variable.

I took that as allow them to write in their own variables and define them vs (what I'm now thinking you meant) new variables WE introduce will show up on the dialog to be defined and written by the worker/script

**Comment by theVKC** [comment]
I was thinking the latter, but see how you could have been confused.

It autofills with the default in a dialog, and the user can update it (either from a droplist or field, depending on what the logic is). That's what I had imagined. Adding new variables at will was not something I had schemed up, as far as I can recall.

**Comment by theVKC** [comment]
@CDPotter, can I get an update on this? I presume it's "in progress"

**Comment by CDPotter** [comment]
Indeed. Strangely when I tried to turn it into a function it worked less reliably.

**Comment by theVKC** [comment]
What does "less reliably" mean? What kind of errors was it throwing?

**Comment by CDPotter** [comment]
Nothing, I select the globvar file using the file select function and nothing seems to happen. I have noticed that it might just be message boxes hiding in the background but it's been about a week or more since I last looked.

**Comment by theVKC** [comment]
Hmmmm. Should we meet on it sometime tomorrow? I'll be in the office.

**Comment by CDPotter** [comment]
Sure shoot me an invite, all I have is a weekly meeting at 1:30-2;30 or so.

**Comment by theVKC** [comment]
Marking this as a sleeper and closing it. @CDPotter has left the agency.
