### ISSUE TITLE
Enhancement Autofill from JOBS/UNEA/SCHL changes to income types/new field

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#286]
Per mentor meeting today there are some changes to the JOBS panel and UNEA panel.

JOBS: 
- New type codes include T - Training P - Service program and R - Rehab Program These will need to be accounted for. 
- There is also a new field around 6, 60 "Hourly Wage" which needs to be read from when those 3 income types are used. 
-This new field seems to move the verif code to the left at 6, 34 and the income type code to 5, 34 (checking to see when this will be installed into MAXIS.)

UNEA
- New type codes include 18 - military training 47 - counted tribal income 48 - trust income 49 non-recurring income. These will need to be accounted for. 
- No other changes to panel presented.

SCHL
- New type codes include 10 - Post-sec tech schl student 12 adult basic ed 14 English as a 2nd language
- No other changes to panel presented.

(side note if anyone knows of any MAXIS scripts that will be affected by the changes post an issue in the MAXIS issue list)

**Comment by CDPotter** [comment]
Luckily it looks like funclib doesn't ever read or manipulate the JOBS/UNEA types so only autofill from SCHL and write to JOBS need changing(due to coordinates). Fix incoming

**Comment by theVKC** [comment]
@CDPotter, is this critical?

**Comment by CDPotter** [comment]
My gut would say no. 

JOBS/UNEA don't read and translate the type codes
SCHL does but that wouldn't inhibit and scripts(fix in pull)
The new hourly wage field is only available in 10/16 and worst case it wouldn't get pulled into case notes for 10/16 cases processed until release. 

The only part I could see as critical is the training case creator bit as that won't work for with a jobs panel in 10/16 forward.

**Comment by theVKC** [comment]
Well, keep an eye out for issues, and if one comes in, go ahead and pull it in yourself.
