### ISSUE TITLE
Can Hennepin provide their SQL server stats CREATE TABLE queries?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#298]
So, this came up at hackathon today. Essentially: Hennepin has built a SQL server for usage stats, and other counties are interested in implementing that (over Access).

If @IlseFerris can provide the SQL server CREATE TABLE queries, that other counties can implement, I'd be happy to document it.

@IlseFerris, you should request the "SQL server CREATE TABLE queries" from SQL Server Management Studio, then upload the .SQL queries to its own folder in the FuncLib repo. From here, other counties can use it.

**Comment by theVKC** [comment]
@IlseFerris: I know you have this... #friendlyreminder

**Comment by theVKC** [comment]
@IlseFerris: still waiting on you to upload this. Just create a new folder called "stats" and within that folder, save the SQL to a file called "sql-table-schema.sql". Pull that in and we'll be square.

**Comment by IlseFerris** [comment]
I'll get this in by the end of the week. Been living the banked months/ABAWD life lately.

**Comment by theVKC** [comment]
Livin' La Vida Banca?
