### ISSUE TITLE
Enhancement add jobs/schl to variable

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#302]
It's been requested that the information pulled from the jobs and schl panels be include more pieces. 

JOBS: Reviewers are getting confused when the script pulls prospective information thinking it was what is budgeted for SNAP(prospective monthly income field) when it's pulled from the prospective side of the jobs panel. 

SCHL: They want to see the FS elig code from this panel. 

I can do this.

**Comment by theVKC** [comment]
@CDPotter, can you confirm that this is, in fact, working in master?

**Comment by CDPotter** [comment]
Checking on my fake case we are in business.

**Comment by theVKC** [comment]
Good deal! Thank you!
