### ISSUE TITLE
Idea: just merge all "write_variable" functions into one

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#310]
Hear me out:

It should be possible to tell what screen you're on based on what position you're in, in PRISM or MAXIS, right? But that might be irrelevant, because...

...perhaps the function can just look for the amount of underscores present. Or even the position on the screen. Or any other number of combinations of factors?

Basically, here's what I'm inspired by:

1. Folks (especially newer scriptwriters) often get confused about the difference between "write_variable" and "write_bullet_and_variable". It'd be nice to provide the option for a bullet as an optional parameter (just pass "false" or "null" if you don't need it). That'd make things easier for newbies.
2. The function names are really long. It'd be nice to shorten it up to something like "write_text".
3. If they all used the exact same parameters, in theory, PRISM and MAXIS could use the same functionality with variables on screen size dynamically determined. This would make bug fixing easier.
4. Less functions to document.
5. Easier expansion into new and unheard of areas (DORD? CORD? WF1? MMIS?).

So, thoughts gang? @MN-Script-Team/funclib-scriptwriters

If this is the direction we should explore, I can try it out instead of #277.

**Comment by lpshanley** [comment]
I love it. Rather that even requiring false or null you could add a handle for undefined so that if a person specifies nothing then its treated like false and if it has a value that value is used. That would be pretty easy to accomplish and it would make things quite nice ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
OK folks, adding this to the to-do. I want to get this done in time for the next round of training.

**Comment by theVKC** [comment]
OK, so @C-Love , @IlseFerris, and I have been talking today about this function (at hackathon) and how it relates to #277. We believe that this resolves the bug in #277 and also could be simpler to use: we could easily work in the bullet functionality with a blank variable:

`call write_variable("Here's some text", "Here's a bullet text")`

It will need to read the screen you're on to determine precisely where to plant the text.

@C-Love and @IlseFerris can't build this due to conflicting priorities. So, I will be taking it on. No ETA.

**Comment by CDPotter** [comment]
Just adding that we ran into a bug today when running NOTES - Arrears management review. It seemed to happen when we reached the end of the writing area on the CAAD note which caused the function to continue to new line and write the rest of the note over the top of the screen and beyond.

**Comment by CDPotter** [comment]
Also I was able to instantly replicate it by trying to write a giant gibberish variable with no spaces.

**Comment by theVKC** [comment]
Well that will always do it. :P

This is on the radar but not a present issue at the moment. If you want up on it, feel free to take it, otherwise it remains on my backlog.
