### ISSUE TITLE
Create two new functions for changelog details: display and update

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#314]
This is in support of https://github.com/MN-Script-Team/DHS-PRISM-Scripts/issues/599. This changelog functionality will allow scriptwriters to directly indicate their updates when they make updates. It creates pop-up boxes **on individual scripts** that tell staff about changes, and then it stores the results in the My Documents folder ala "update worker signature", so that way users aren't bombarded with changes they're unaware of.

I had originally been working on this as a separate script with @RoberT-1000, but decided to expand this functionality to allow pop-ups directly in scripts. This should resolve several concerns (in both MAXIS and PRISM) with users being unaware of script updates.

I could use some help in testing this. Specifically, imagining @CDPotter helping coordinate a MAXIS testing/rollout phase with @C-Love and @IlseFerris, and myself coordinating the project as-a-whole, as well as coordinating PRISM work with @RobertFewins-Kalb and @levesswe. If you all accept this task, let me know and I'll add you (then we should find a date to build the remaining functionality).   

The functions themselves will be pulled in quickly, but once they're confirmed and deployed we'll need folks to test the functionality and run it through the ringer. It's likely each script will need to be updated with changelog items. The pull requests are coming in shortly.

**Comment by CDPotter** [comment]
I'm interested.

**Comment by theVKC** [comment]
New functions are in master branch. I'll be pulling my changelog script into PRISM shortly, and I'll paste a link on this thread. Then, you-all can copy the functionality to a few scripts and perhaps test changelogs on some agency custom stuff?

**Comment by theVKC** [comment]
changelog,vbs (see bottom for usage example, folks): https://github.com/MN-Script-Team/DHS-PRISM-Scripts/blob/master/utilities/changelog.vbs

**Comment by theVKC** [comment]
Bump!

Can I get some feedback from users in two separate agencies showing that this is, in fact, working? It's in master branch across PRISM, not sure about MAXIS.

Perhaps @RoberT-1000 and @levesswe can test for Anoka, and @IlseFerris can confirm with Hennepin (if it's been at all deployed in master branch).

Alternatively, let's bring in @heatherallen: can you check this out in PRISM for Scott County? Are you getting the changelog updates for scripts we pushed out yesterday? Any of that stuff I emailed about today (regarding "testing") should probably display if your staff have used it before.

**Comment by heatherallen** [comment]
@theVKC I am not getting the changelog updates, I opened the NOCS, Prorate Calculator, and MAXIS finder and none showed the changelog.

**Comment by theVKC** [comment]
It's possible they haven't been edited since the last time you used it, perhaps it initialized that first time. Kelly just sent a change for ACTIONS - case transfer, how is that one?

**Comment by heatherallen** [comment]
Still nothing :(

**Comment by theVKC** [comment]
Well it's possible that you hadn't used it since we added the new functionality.

Can you go into your scripts-local-changelog-update.txt file (within your My Documents folder), and edit the case transfer entry to say "Initial version."? By doing that, I do believe it'll reset to make it appear you'd used the script before.

**Comment by heatherallen** [comment]
When I went in to change it this was the text that was in the file after case transfer:
County, Office, Team and Position fields now have length requirements.
When I changed to Initial version, and I tried to run case transfer again no change log dialog popped up. (not sure if it should have if I was resetting it)

**Comment by theVKC** [comment]
Hmmmm. Well, that tells me at least one thing. It's writing the file.

In any case, @MN-Script-Team/prism-wright has confirmed that this is working over here. So there's one agency.

**Comment by theVKC** [comment]
@heatherallen: can you run the court prep worksheet script? Even if it doesn't work? Then, can you check the text file and see if it's there?

@RoberT-1000 is about to have a fix pushed out for it, so we can use that to test/confirm.

**Comment by theVKC** [comment]
I just heard from Jackson/Cottonwood saying they are seeing the text file being created. I'm calling this one a day, folks.

@CDPotter, can you let me know when changelog functionality is fully deployed on the MAXIS side? You should probably make an issue for it already (if you haven't) and paste the URL to this issue into that issue (to create a dynamic link).

**Comment by heatherallen** [comment]
@theVKC I just ran it and no change log pop up and no change in the change log yet, it states initial version currently.

**Comment by theVKC** [comment]
That's good. Now I'll push the new feature and then you can try again, and let me know if you see the box. Try again in 10 minutes or so?

**Comment by theVKC** [comment]
This should have closed due to multiple agencies reporting it's working. Nice job testing, folks.
