### ISSUE TITLE
Replace "navigate_to_XXXX_screen" with unified "navigate_to()" function

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#318]
Any thoughts from folks?

**Comment by theVKC** [comment]
Syntax imagined: 
* PRISM: `call navigate("CAAD")`
* MAXIS: `call navigate("STAT/MEMB")`

**Comment by theVKC** [comment]
Can I get feedback on this @MN-Script-Team/prism-scriptwriters @MN-Script-Team/funclib-scriptwriters @MN-Script-Team/maxis-scriptwriters?

**Comment by CDPotter** [comment]
Seems like a good idea to me.

**Comment by theVKC** [comment]
Also a thought, `navigate("STAT/MEMB")` vs `navigate_to("STAT/MEMB")`.

**Comment by GayS** [comment]
I like the simplification!

**Comment by C-Love** [comment]
I think this is a good idea. Also, MMIS...

**Comment by theVKC** [comment]
@C-Love, @CDPotter, @GayS: what do you prefer, `navigate("screen")` or `navigate_to("screen")`. I think the latter might be easier for beginners to digest, so I lean toward that.

**Comment by CDPotter** [comment]
I could see the value in the latter.

**Comment by C-Love** [comment]
I defer to you on that, I don't think I have much of a preference on this part.

**Comment by GayS** [comment]
I don't have a preference either.

**Comment by IlseFerris** [comment]
I don't have a strong preference either, but love the idea of unifying the functions.

**Comment by lpshanley** [comment]
With naming convention as long as its not taken “to far” like this_would_be_a_touch_to_long_for_a_function() I think generally more can be more.

I am a fan of navigate_to

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
Yes! Agreed! We're going with `navigate_to()` and this is on. Anyone want to take it? I'm hoping to wrap it in the next week or so.

**Comment by theVKC** [comment]
I'm taking it.

**Comment by theVKC** [comment]
Marking as a sleeper, no idea when we can wrap this.
