### ISSUE TITLE
Possible issue on changelog_display: possibly not closing WScript.Shell

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#323]
We are getting reports of users getting a "permission denied" error for the changelog file.

Near the end of the function, a `set objTextStream = nothing` was used instead of `objTextStream.Close`. I am guessing this is the culprit, as it wouldn't explicitly close the file.

On it. @C-Love will coordinate a test at Ramsey.

**Comment by theVKC** [comment]
Pulled in, @C-Love! Please test away!

**Comment by C-Love** [comment]
On it. I think I actually have 2 testers. I will send them out an email and will make sure that they don't hit the error tomorrow and confirm on Thursday.

**Comment by C-Love** [comment]
Ok - we have a good start. One of my testers was able to run his first script of the day. It required a restart but then his scripts worked.

**Comment by theVKC** [comment]
This is now in release @C-Love. I'm going to close it for now. If the problem persists after restarts with release-branch users, let me know.

**Comment by kaleykobber** [comment]
We are still experiencing issues. I will send an email to Veronica and Charles with a summary of the issues. Any effort to assist with troubleshooting this is greatly appreciated, it is affecting more of our users, and is limiting their access to scripts.

**Comment by theVKC** [comment]
@kaleykobber, let's address this one offline. I am beginning to suspect a problem other than the script.

If any other counties are still running into issues, please please please say something so we can try and diagnose together.

Possible culprits:

1. Lack of access to the file
2. The file still isn't closing
3. Some problem in chain loading somewhere
4. API settings making two scripts run at the same time

**Comment by kaleykobber** [comment]
Sounds good. Thanks!
