### ISSUE TITLE
FUNCTION month_change: update docstring

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#333]
I believe this may have been used in NOTES - APPROVED PROGRAMS at one time, but since has been removed. @C-Love, @CDPotter @RoberT-1000 can anyone confirm?

**Comment by RoberT-1000** [comment]
That doesn't look like my code. I have no idea where that came from.

**Comment by RoberT-1000** [comment]
@C-Love? I see some MsgBox bling.

**Comment by C-Love** [comment]
This is definitely my code... FSS Status Change uses it. (Though I think it is also defined there because I pulled that in first... or something)

I keep forgetting about this function.

**Comment by IlseFerris** [comment]
@C-Love, would you be willing to look at the comments/instructions for the function? I don't know if I did it justice. 
Also we should keep this in the FuncLib if it's something we anticipate being used :)

**Comment by theVKC** [comment]
@C-Love, I'd love it if you could modify that text to make sure it's clear why it's used.
