### ISSUE TITLE
Create Option so ChangeLog can be disabled in Global Variables

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/BZS-FuncLib#349]
Since we are having county specific issues with ChangeLog, we need an option to disable it to allow workers to continue to use scripts. Just and If - then in the function.

Pulling this in shortly

**Comment by theVKC** [comment]
I'm fast-tracking this one because of the time-sensitive nature here. Since it's county specific, we'll do little testing.

When I pull this in, @C-Love, please check that master works as expected, and @IlseFerris, please check that master works as expected for you.

**Comment by C-Love** [comment]
Yep - working fine - I can turn it on and off with the quick change of a Boolean

**Comment by theVKC** [comment]
Resolved by #351 and #350.
