### ISSUE TITLE
ten_day_cutoff_check needs 2017 cut off dates

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#352]
Te19.132 has been updated to reflect the 2017 cut off dates (I only had to push a few times :)).

function now needs to be updated with this information. Assign to me.

**Comment by theVKC** [comment]
@IlseFerris: is this causing a critical issue? Collecting this for statistics purposes.

**Comment by IlseFerris** [comment]
The information that is input into case note would certainly be incorrect. Since this information can be tied to worker action (or lack thereof), I would call it critical.

**Comment by theVKC** [comment]
Score one for critical. Thank you!
