### ISSUE TITLE
Create MS Outlook functions

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#355]
Pretty simple...create functions for creating an outlook appointment, a task and an email. 

I'm working on this at my county, so this can get assigned to me.

**Comment by theVKC** [comment]
Please do. I need this for PRISM. https://github.com/MN-Script-Team/DHS-PRISM-Scripts/issues/464 is pending for this very thing (although I might remove that script from primary use until this function is ready).

I'd be happy to be your tester for this. Thanks @IlseFerris!
