### ISSUE TITLE
Enhancement - PowerPad - CASE/PERS navigation button to be added to powerpad

### ISSUE THREAD

**Issue by MiKaylaH22** [MN-Script-Team/BZS-FuncLib#369]
Family workers use this navigation heavily. Also when a case is to be appl'd it can help reduce the amount of duplicate PMI's being issued.

**Comment by theVKC** [comment]
You may have noticed this (I assume that's why it's closed), but FuncLib isn't the right place for this MAXIS-specific issue. :)

**Comment by theVKC** [comment]
(Entered here publicly in case future scriptwriters stumble on a similar dilemma.)
