### ISSUE TITLE
Function Prism_case_number_validation does not validate case numbers with "." or a space

### ISSUE THREAD

**Issue by KyleNelson-Hennepin** [MN-Script-Team/BZS-FuncLib#372]
While trying out the Notes/E-Filing script, I noticed an issue where the script wouldn't work if I entered a case number in manually.

I looked at it with @IlseFerris today and we determined it was an issue with the Prism_case_number_validation function. The function only returns a case number as valid if it's formatted with a dash between numbers.

This works for when the case number is obtained via the PRISM_case_number_finder function, but does not work when a user manually enters a case number, unless the user enters it with a dash between the numbers.

If manual entry is an option in the dialog box, shouldn't it allow a case number with a space, a dash, or a period between the numbers? 

Can we update the PRISM_case_number_validation function to allow case numbers with a space or period between numbers? Or would that mess up other scripts that use this function?

**Comment by KyleNelson-Hennepin** [comment]
Ok, never mind - I'll close the issue. That script was one of the first scripts I reviewed - after reviewing several more it looks like most or all scripts are written assuming the case number has the dash. It looks like most scripts tell the user that the case number should be formatted xxxxxxxxxx-xx either in the dialog box or in an error message if it's not formatted that way.

**Comment by theVKC** [comment]
You know what though, @KyleNelson-Hennepin?

I could see value in modifying this to allow for the conversion of a space or period into a dash for use in scripts... @gretchent74 and I just talked about that and felt it might be valuable. Would you be at all interested in submitting an enhancement to the function that allows for this? Could be a good opportunity to get FuncLib experience! :)

**Comment by KyleNelson-Hennepin** [comment]
Sure I can do that. I'm working with @IlseFerris on Thursday, so I'll work on it then. I definitely need some experience to get used to how this whole process works, and this seems like it would probably be a good easy-ish project for me to take on.

To help me when I go to work on this on Thursday, and to make sure I'm understanding correctly, is this correct?:

The Prism_case_number_validation function is called with a number that the script is wanting to validate as true/false, to verify if it's actually a case number. Currently, if that number is formatted with a space or a period, the function will return a false value; it will only return a true value if it's formatted with a dash. After my edit to the function, if the case number is formatted with a space or a period, it will return a true value.

**Comment by theVKC** [comment]
Yes, and... :)

I would also suggest having it instead modify the space or period to have a dash, this way it's used evenly across function. The `replace()` function should handle that nicely.

**Comment by theVKC** [comment]
Pulled in, @KyleNelson-Hennepin! Welcome to your first commit!

Now we test. This is a minor enhancement, so I don't think it would need much. @KyleNelson-Hennepin, in a few minutes, you should see this change reflected in the master branch.

I'm going to say we should have an additional tester in another agency for safe confirmation. @levesswe, can you have someone in Anoka check to see if any master-branch scripts using this function now allow spaces as well as dashes?

**Comment by levesswe** [comment]
I tested a few scripts and this fix works dandy!   Dashes, periods, or spaces, it worked like a charm.  Thanks! :)

**Comment by theVKC** [comment]
Good deal! @KyleNelson-Hennepin: since you don't have a complete formal test team at Hennepin, I'm going to call this one complete given @levesswe's quick review.

Nice job gang! What a great first commit, @KyleNelson-Hennepin! You're a very welcome addition to the team. :)

**Comment by IlseFerris** [comment]
@KyleNelson-Hennepin  for the win!
