### ISSUE TITLE
BUG in navigate_to_MAXIS_screen - searching for 'function'

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/BZS-FuncLib#373]
Navigate_to_MAXIS_screen uses EMSearch to find the MAXIS Function of the current MAXIS screen we are currently on. This will prevent the script from going out to SELF if we are navigating within the same function area.

The search term was changed to 'function: " BUT the MAXIS screen always has 'Function: ".

This is severely breaking the training case creator. I am updating.

**Comment by theVKC** [comment]
@C-Love: please see my comment on #374. Your pull is causing a merge conflict. Wah wahhhhh.

**Comment by C-Love** [comment]
I've tested this in master and it appears to fix all my Training Case Creator and Nav problems! Woohoo! Good to go to release.
