### ISSUE TITLE
Bug with Returned Mail WCOM

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/BZS-FuncLib#378]
Two issues, the dialog loop checks for worker sig, but there isn't a space for one in the dialog (it works if there is a saved worker sig on the user's computer). It also needs handling for multiple recipient memos (such as an AREP), which have an extra screen after PF9.

**Comment by theVKC** [comment]
FuncLib on this?

**Comment by courtrightd** [comment]
Oops - nope, wrong issue list.  Sorry.

**Comment by theVKC** [comment]
No worries. :)
