### ISSUE TITLE
Function for Sending a SPEC/MEMO to all applicable recipients in MAXIS

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#379]
This is code we use repeatedly in NOTICES scripts. Makes sense that it's a function: 

![image](https://cloud.githubusercontent.com/assets/10836829/24716715/84f1cf4e-19f5-11e7-9d43-cddb7a97c59c.png)

I can take this, or @courtrightd said he may be interested at some point adding this.

**Comment by theVKC** [comment]
ETA @IlseFerris or @courtrightd?

**Comment by IlseFerris** [comment]
@courtrightd do you want this? I can take it otherwise.

**Comment by courtrightd** [comment]
You can have it if you want, I've got plenty of other stuff to knock out here.

**Comment by IlseFerris** [comment]
Sounds good. Assign to me. I'll get it done at the Ramsey Hackathon next week.

**Comment by IlseFerris** [comment]
I just tested this function by adding it into a local version of DAIL - FMED DEDUCTION that I am testing. Working well. Thank you @C-Love!

**Comment by theVKC** [comment]
Thank you for testing, @IlseFerris! 

@C-Love, I'm pulling this in now. Please let me know if it's working in master (once the pull request is done) and I'll pull it into release.

**Comment by IlseFerris** [comment]
Tested in master by adding function into a script, and running it locally. Worked perfectly!

**Comment by C-Love** [comment]
Tested in master as well. Working as expected.
