### ISSUE TITLE
Statistics: apparently SQLite works too instead of Access...

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#382]
Cool discovery which could be exceptionally helpful!

```vb.net 
run "C:\DHS-PRISM-Scripts\databases\sqlite3.exe C:\DHS-PRISM-Scripts\databases\test.db " & chr(34) & "insert into tbl1 values('hey there');" & chr(34)
```

If SQLite's binary is present in the databases folder (or anywhere really), standard SQL can be used to pass BlueZone Scripts content to a SQL table. This does NOT require any software installed (unlike the current situation which uses Access or SQL Server). With this, I could build a simple HTML interface to let supervisors see the content or generate simple reports.

SQLite is open source (https://www.sqlite.org/about.html) and the whole thing took me less than an hour. I think we could use @IlseFerris' SQL commands to create a .db file, and that could be easily distributed and implemented everywhere.

I'm not likely to implement this during April, but I was hoping to work on stats in May, and this would be part of that. Perhaps we can finally provide formal documentation for it, once we can verify it's reasonably easy to implement for non-IT-folks.

(Putting this here because script_end_procedure invokes the call to SQL or Access)

**Comment by IlseFerris** [comment]
This is really awesome! Might be something @KyleNelson-Hennepin may be interested in using/testing until CS goes lives on SQL.

**Comment by KyleNelson-Hennepin** [comment]
I really need to spend most of my time reviewing scripts and doing what I can to prepare to roll out the state scripts for Hennepin workers, so I don't think I'll have any time for this unfortunately. 

Sounds cool though! I'm all for doing what we can to make things easier to implement! :-)
