### ISSUE TITLE
Navigate_to_PRISM function doesn't work if F1'd into a PRISM submenu

### ISSUE THREAD

**Issue by KyleNelson-Hennepin** [MN-Script-Team/BZS-FuncLib#385]
The navigate_to_PRISM function doesn't work if the user is F1'd into a PRISM submenu (such as CALI's Caseload Position List, or the Case Search Help Routine if you F1 on a case number field). The function doesn't work because PRISM doesn't allow you enter data into the direct command line or to navigate between screens while you're F1'd in a submenu.

This was a concern for the BULK/list generator-CALI PRISM script (see: issue #783).

@CDPotter recommended that something like this could be built into the navigate_to_PRISM function:

DO
Type CAAD on nav bar
Check to see if we went to CAAD
if we didn't PF3
LOOP until screen_check = nav_screen

I can take this on if we think it's a good idea.

**Comment by theVKC** [comment]
I think it's a great idea, and was always intended for this. :)

**Comment by KyleNelson-Hennepin** [comment]
Cool - I got the code written up, will double-check it today, planning on submitting the pull request tomorrow (Friday).

It's essentially this:
Do
Try to navigate to CAAD (or CAST if we were already on CAAD)
Check to see if we went to CAAD (or CAST if we were on CAAD)
If not, PF3 and start the loop over
Loop until we see that we navigated to CAAD (or CAST if we were on CAAD)
Then actually navigate to the screen called in by the function
