### ISSUE TITLE
Script_end_procedure enhancement: Fix scripts issue w/ ESSO password manager software

### ISSUE THREAD

**Issue by KyleNelson-Hennepin** [MN-Script-Team/BZS-FuncLib#388]
Many Hennepin County PRISM & MAXIS workers use password manager software called ESSO. ESSO is always on, running in the background. If you run a script while ESSO is running (in the background), most scripts will pause and not work correctly.

To get around this, we currently instruct users to manually pause or shut down ESSO before running scripts. However, @IlseFerris and I have written some code to get around this issue without having the user do anything.

The first half of the code goes in Hennepin County's global variables files. We determine if ESSO is installed on the user's computer. If ESSO is found, we force ESSO to close and we set a variable called "using_ESSO" to true.

The second half of the code goes in the script_end_procedure function. If using_ESSO is set to true, then we open ESSO back up in the background.

The end result will be that when a worker runs a script, if ESSO is installed on their computer, ESSO will be closed, and ESSO will then be restarted at the end of the script. For non-Hennepin County workers, or Hennepin County workers who do not have ESSO installed, nothing will occur.

We'd like to get this code into the FuncLib before the upcoming PRISM/FuncLib freeze, so I'll submit a pull request.

**Comment by KyleNelson-Hennepin** [comment]
Done - see pull request #389

**Comment by IlseFerris** [comment]
I've also tested this code for users with and without ESSO. Working as intended. Please accept this pull request.

**Comment by IlseFerris** [comment]
Can we reopen this? We've tested this, and it would greatly beneficial to our users. Thank you!

**Comment by theVKC** [comment]
@IlseFerris: reopened. Can you review the pull request #390 and mark it as approved?
