### ISSUE TITLE
CREATE_OUTLOOK_APPOINTMENT bug: appointment reminder only working in FALSE

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#392]
Bug in option to set the appt_reminder to TRUE. Currently users are only able to set this to FALSE due to the appt_reminder variable in the TRUE statement. 

Assign to me. Testing the fix locally has been successful. 

![image](https://user-images.githubusercontent.com/10836829/29339502-0f045ab0-81e0-11e7-986d-d22dcf068cb8.png)

**Comment by theVKC** [comment]
Getting around to FuncLib now!

@IlseFerris, any update on this? Is it working? Want to pull it in?

**Comment by IlseFerris** [comment]
It's working, and I'll pull it in.

**Comment by theVKC** [comment]
Issue falsely closed. @IlseFerris: I think we should stop saying "resolved #X" until it's ready for release. It keeps closing issues before we've tested.

Pull request in: can we test?
