### ISSUE TITLE
Training Case Creator function write_panel_to_MAXIS_JOBS bug: needs verif column update

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#397]
This is associated with MAXIS scripts issue #2999. Column for income type and jobs verification codes changed 10/16. Coding that was added at the time doesn't account for years that are not 2016 or 2017. 

Assign this issue to me.

**Comment by theVKC** [comment]
Any update @IlseFerris?

**Comment by theVKC** [comment]
Can I get confirmation that these are working in master branch @IlseFerris?

**Comment by theVKC** [comment]
Confirmed by @C-Love to be working!
