### ISSUE TITLE
ADD_JOBS_TO_VARIABLE function for JOBS bug: needs verif column update

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#398]
Associated with issue #397 

This is associated with MAXIS scripts issue #2999. Column for income type and jobs verification codes changed 10/16. Coding that was added at the time doesn't account for years that are not 2016 or 2017. 

Assign this issue to me.

**Comment by C-Love** [comment]
The function write_panel_to_MAXIS_JOBS also needs the columns updated. 

I will take this.

**Comment by theVKC** [comment]
Can I get confirmation that these are working in master branch @IlseFerris?

**Comment by C-Love** [comment]
Both of these functions are working wonderfully in MASTER now.

**Comment by theVKC** [comment]
Pushed to release.
