### ISSUE TITLE
Create custom function for determining if the footer month is current month + 1

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#51]
This would be helpful for many reasons. :)

@IlseFerris has this one in the hopper already.

**Comment by theVKC** [comment]
@IlseFerris, remind me: did this happen?

**Comment by IlseFerris** [comment]
I don't think it did. Can you remind me what you wanted for this?  It's been about 6 months (yikes!)

**Comment by theVKC** [comment]
I don't remember, let's close it.

**Comment by IlseFerris** [comment]
works for me!
