### ISSUE TITLE
New fucntion idea: ‘Excel list from MAXIS’ function

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/BZS-FuncLib#91]
Same coding used in all scripts that use excel list.

@RobertFewins-Kalb, you got this?

**Comment by theVKC** [comment]
@RobertFewins-Kalb, any progress? No worries if not. @IlseFerris, if you and Robert don't think it's vital, I'm going to close the issue.

**Comment by IlseFerris** [comment]
If @RobertFewins-Kalb can't take it, maybe @CDPotter or @courtrightd, otherwise let's close this

**Comment by theVKC** [comment]
[waits patiently for @RobertFewins-Kalb to get through his GitHub email for the day]

**Comment by RobertFewins-Kalb** [comment]
It takes a while...

**Comment by RobertFewins-Kalb** [comment]
I'm not familiar with the background on this function, but I could whip something up.

**Comment by RobertFewins-Kalb** [comment]
@IlseFerris , could you provide some more input as to what you are looking for?

**Comment by IlseFerris** [comment]
I'm pretty sure it was just this:
'OPENS A NEW EXCEL SPREADSHEET
Set objExcel = CreateObject("Excel.Application") 
objExcel.Visible = True  
Set objWorkbook = objExcel.Workbooks.Add() 

I think this was one of those "Hey Ilse, throw this issue up on GitHub" and we forgot about it.  If this isn't it, we can close the issue. @RobertFewins-Kalb care to throw in your two cents?

**Comment by theVKC** [comment]
I was thinking `CALL create_Excel_list_from_MAXIS("ACTV")`. Thoughts?

**Comment by IlseFerris** [comment]
Sounds good to me.

**Comment by theVKC** [comment]
@RobertFewins-Kalb?

**Comment by IlseFerris** [comment]
If this is all that is to it, I can get this done.  Like actually do it, not just say I'm going to do it, and then do a thousand other things (my bad).

**Comment by theVKC** [comment]
I think it's actually pretty complicated. I'm wondering if @RobertFewins-Kalb has anything on it.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, haven't heard from you on this yet.

**Comment by theVKC** [comment]
I'll take it

**Comment by theVKC** [comment]
It's unlikely I can do this this month. Marking as help wanted.

**Comment by theVKC** [comment]
If nobody takes this before hackathon Monday, I will clear it.
