### ISSUE TITLE
Check for Duplicate Custom Functions in MAXIS and PRISM FuncLib

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#92]
There was a problem with the Anoka County PRISM scripts BETA main menu. The custom function "run_another_script" was located in both FuncLibs. We need to find and eradicate all duplicate custom functions to eliminate critical errors.

**Comment by RobertFewins-Kalb** [comment]
I have already removed "run_another_script" from the PRISM FuncLib

**Comment by theVKC** [comment]
I think it's time we just take all of them and create a single file. This shouldn't be controversial, and would obviously help all scriptwriters with each others' work.

**Comment by IlseFerris** [comment]
You can assign this to me

**Comment by RobertFewins-Kalb** [comment]
This is probably already done

Sent from my iPhone

On Sep 18, 2015, at 7:19 AM, Ilse Ferris <notifications@github.com<mailto:notifications@github.com>> wrote:


You can assign this to me

-
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/BZS-FuncLib/issues/92#issuecomment-141434509>.



Click here<https://www.mailcontrol.com/sr/mYly9ePJYKXGX2PQPOmvUtXHXnVjuGgHZqTXDfvarQA5EWxbyL2QsZTV!DiD!7MC6cmMVupgE!9jDxGYc2QXWA==> to report this email as spam.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by IlseFerris** [comment]
Even better :)
